title: blank
first_name: Aton
middle_name: null
last_name: Kamanda
description: null
email: aton.kamanda@umontreal.ca
icon: /ak
url: https://atonkamandatest.github.io
baseurl: null
last_updated: true
impressum_path: null
navbar_fixed: true
footer_fixed: true
max_width: 500px
serve_og_meta: false
og_image: null
github_username: atonkamanda
gitlab_username: null
twitter_username: AtonKamanda
linkedin_username: null
scholar_userid: null
orcid_id: null
medium_username: null
quora_username: null
publons_id: null
research_gate_profile: null
blogger_url: null
work_url: null
keybase_username: null
wikidata_id: null
dblp_url: null
stackoverflow_id: null
rss_icon: false
contact_note: >
  You can even add a little note about which of these is the best way to reach
  you.
google_analytics: UA-XXXXXXXXX
panelbear_analytics: XXXXXXXXX
blog_name: Papers review
blog_description: 'Blog articles about neuroscience, deep learning and reinforcement learning.'
permalink: '/blog/:year/:title/'
pagination:
  enabled: true
disqus_shortname: al-folio
collections:
  papers_review:
    defaults:
      layout: post
    output: true
    permalink: '/papers_review/:path/'
  ideas:
    defaults:
      layout: post
    output: true
    permalink: '/ideas/:path/'
  projects:
    output: true
    permalink: '/projects/:path/'
  fav_book:
    output: true
    permalink: '/teaching/:path/'
news_limit: 5
markdown: kramdown
highlighter: rouge
highlight_theme: github
kramdown:
  input: GFM
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1
include:
  - _pages
exclude:
  - bin
  - Gemfile
  - Gemfile.lock
  - vendor
keep_files:
  - CNAME
  - .nojekyll
  - .git
plugins:
  - jekyll/scholar
  - jekyll-diagrams
  - jekyll-email-protect
  - jekyll-feed
  - jekyll-github-metadata
  - jekyll-paginate-v2
  - jekyll-sitemap
  - jekyll-target-blank
  - jekyll-twitter-plugin
  - jemoji
  - jekyll-redirect-from
whitelist:
  - jekyll-redirect-from
github:
  - metadata
scholar:
  last_name: Einstein
  first_name:
    - Albert
    - A.
  style: apa
  locale: en
  source: /_bibliography/
  bibliography: papers.bib
  bibliography_template: bib
  bibtex_filters:
    - latex
    - smallcaps
    - superscript
  replace_strings: true
  join_strings: true
  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details
  query: '@*'
jekyll-diagrams: null
enable_google_analytics: false
enable_panelbear_analytics: false
enable_mansory: true
enable_math: true
enable_tooltips: false
enable_darkmode: false
enable_navbar_social: true
enable_project_categories: true
enable_medium_zoom: true
academicons:
  version: 1.9.0
  integrity: >-
    sha512-W4yqoT1+8NLkinBLBZko+dFB2ZbHsYLDdr50VElllRcNt2Q4/GSs6u71UHKxB7S6JEMCp5Ve4xjh3eGQl/HRvg==
bootstrap:
  version: 4.5.2
  integrity:
    css: >-
      sha512-MoRNloxbStBcD8z3M/2BmnT+rg4IsMxPkXaGh2zD6LGNNFE80W3onsAhRcMAMrSoyWL9xD7Ert0men7vR8LUZg==
    js: >-
      sha512-M5KW3ztuIICmVIhjSqXe01oV2bpe248gOxqmlcYrEzAvws7Pw3z6BK0iGbrwvdrUQUhi3eXgtxp5I8PDo9YfjQ==
fontawesome:
  version: 5.14.0
  integrity: >-
    sha512-1PKOgIY59xJ8Co8+NE6FZ+LOAZKjy+KY8iq0G4B3CyeY6wYHN3yt9PW0XpSriVlkMXe40PTKnXrLnZ9+fkDaog==
jquery:
  version: 3.5.1
  integrity: >-
    sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==
mathjax:
  version: 3.2.0
mansory:
  version: 4.2.2
  integrity: sha256-Nn1q/fx0H7SNLZMQ5Hw5JLaTRZp0yILA/FRexe19VdI=
mdb:
  version: 4.19.1
  integrity:
    css: >-
      sha512-RO38pBRxYH3SoOprtPTD86JFOclM51/XTIdEPh5j8sj4tp8jmQIx26twG52UaLi//hQldfrh7e51WzP9wuP32Q==
    js: >-
      sha512-Mug9KHKmroQFMLm93zGrjhibM2z2Obg9l6qFG2qKjXEXkMp/VDkI4uju9m4QKPjWSwQ6O2qzZEnJDEeCw0Blcw==
popper:
  version: 2.4.4
  integrity: >-
    sha512-eUQ9hGdLjBjY3F41CScH3UX+4JDSI9zXeroz7hJ+RteoCaY+GP/LDoM8AO+Pt+DRFw3nXqsjh9Zsts8hnYv8/A==
medium_zoom:
  version: 1.0.6
  integrity: sha256-EdPgYcPk/IIrw7FYeuJQexva49pVRZNmt3LculEr7zM=
